// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFJFl66Fhc4TYkNhjKH1Wi6baTtb4E2k',
    appId: '1:4406014822:web:1c16660d44a3b884c90ea7',
    messagingSenderId: '4406014822',
    projectId: 'myliste-app',
    authDomain: 'myliste-app.firebaseapp.com',
    storageBucket: 'myliste-app.firebasestorage.app',
    measurementId: 'G-C46GEPE94T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-79NGoYTS4WxINzQvrVo8suUPNyhnvHM',
    appId: '1:4406014822:android:c434b47ce9c290d2c90ea7',
    messagingSenderId: '4406014822',
    projectId: 'myliste-app',
    storageBucket: 'myliste-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9l0OpdLoJDVwpi5yTPDOGk4Gityvi1I',
    appId: '1:4406014822:ios:3f5c2921f6aa5d6cc90ea7',
    messagingSenderId: '4406014822',
    projectId: 'myliste-app',
    storageBucket: 'myliste-app.firebasestorage.app',
    iosClientId: '400867505180-04v417e92s2jl4qrcqb58pgu726qvv0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myListe',
  );

}